server:
  port: 1002

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: orderservice
  cloud:
    nacos:    #nacos负载配置
      server-addr: http://127.0.0.1:8848 # nacos服务地址
      discovery:
        cluster-name: BJ  #定义地域化集群

# eureka服务注册
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka


logging:
  level:
    xu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#负载均衡规则
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则


#饥饿加载：每次请求，都会重新创建连接链路
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice
    # -XXXservice  (多个服务)