server:
  port: 1001

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_user?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.jdbc.Driver
  application:
      name: userserver # user的服务名称
  cloud:
    nacos:    #nacos负载配置
      server-addr: http://127.0.0.1:8848 # nacos服务地址
      discovery:
        cluster-name: BJ  #定义地域化集群

# eureka服务注册
#eureka:
#  client:
#    service-url:  # eureka的地址信息
#      defaultZone: http://127.0.0.1:10086/eureka

logging:
  level:
    xu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS